name: Markdown Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run markdownlint
        uses: nosborn/github-action-markdown-cli@v3
        with:
          files: articles/**/*.md
