name: Sync Articles to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "articles/**"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3

      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: long-910/long-910.github.io
          path: target
          token: ${{ secrets.GH_PAT }}

      - name: Process and sync articles
        run: |
          # 記事ファイルを処理
          for file in articles/*.md; do
            if [ -f "$file" ]; then
              # ファイル名をそのまま使用
              filename=$(basename "$file")
              target_file="target/_posts/$filename"
              
              # フロントマターを変換
              temp_file=$(mktemp)
              
              # フロントマターの変換処理
              awk -v filename="$filename" '
              BEGIN { in_frontmatter = 0; frontmatter_done = 0; }
              /^---$/ {
                if (!in_frontmatter) {
                  in_frontmatter = 1;
                  print "---";
                  print "layout: post";
                  next;
                } else {
                  in_frontmatter = 0;
                  frontmatter_done = 1;
                  print "---";
                  next;
                }
              }
              in_frontmatter {
                if ($0 ~ /^title:/) {
                  print $0;
                  next;
                }
                if ($0 ~ /^emoji:/) {
                  print "img_path: /assets/img/logos";
                  print "image:";
                  print "  path: logo-only.svg";
                  print "  width: 100%";
                  print "  height: 100%";
                  print "  alt: Zenn";
                  next;
                }
                if ($0 ~ /^type:/) {
                  print "category: [Tech]";
                  next;
                }
                if ($0 ~ /^topics:/) {
                  print "tags:" substr($0, 8);
                  next;
                }
                if ($0 ~ /^published_at:/) {
                  print "date:" substr($0, 14);
                  next;
                }
                next;
              }
              frontmatter_done && !printed_link {
                print "\n\n---\n\nこの記事は[Zenn](https://zenn.dev/long910/articles/"substr(filename, 1, length(filename)-3)")でも公開しています。";
                printed_link = 1;
              }
              { print; }
              ' "$file" > "$temp_file"
              
              # 既存ファイルとの比較
              if [ -f "$target_file" ]; then
                # ファイルの内容を比較
                if ! cmp -s "$temp_file" "$target_file"; then
                  echo "Updating existing file: $filename"
                  cp "$temp_file" "$target_file"
                else
                  echo "No changes detected in: $filename"
                fi
              else
                echo "Creating new file: $filename"
                cp "$temp_file" "$target_file"
              fi
              
              # 一時ファイルを削除
              rm "$temp_file"
            fi
          done

      - name: Commit and push changes
        run: |
          cd target
          git config --global user.name "long-910"
          git config --global user.email "7323488+long-910@users.noreply.github.com"
          git add _posts/
          git commit -m "Sync articles from Zenn repository" || echo "No changes to commit"
          git push
